package com.linkpets.core.dao;

import java.util.List;
import java.util.Map;

import com.linkpets.core.model.CmsAdoptApply;

public interface CmsAdoptApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_apply
     *
     * @mbg.generated Sat May 18 15:13:36 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String applyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_apply
     *
     * @mbg.generated Sat May 18 15:13:36 GMT+08:00 2019
     */
    int insert(CmsAdoptApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_apply
     *
     * @mbg.generated Sat May 18 15:13:36 GMT+08:00 2019
     */
    int insertSelective(CmsAdoptApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_apply
     *
     * @mbg.generated Sat May 18 15:13:36 GMT+08:00 2019
     */
    CmsAdoptApply selectByPrimaryKey(String applyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_apply
     *
     * @mbg.generated Sat May 18 15:13:36 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(CmsAdoptApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_apply
     *
     * @mbg.generated Sat May 18 15:13:36 GMT+08:00 2019
     */
    int updateByPrimaryKey(CmsAdoptApply record);

	List<Map<String, Object>> getList(Map<String, Object> param);

    int getApplyCount(String syncDate);

    List<CmsAdoptApply> getExpiredAdoptApplyList();
}