package com.linkpets.core.dao;

import com.linkpets.core.model.CmsAdoptOrgActivity;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CmsAdoptOrgActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_org_activity
     *
     * @mbg.generated Sun Aug 25 21:32:26 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_org_activity
     *
     * @mbg.generated Sun Aug 25 21:32:26 CST 2019
     */
    int insert(CmsAdoptOrgActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_org_activity
     *
     * @mbg.generated Sun Aug 25 21:32:26 CST 2019
     */
    int insertSelective(CmsAdoptOrgActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_org_activity
     *
     * @mbg.generated Sun Aug 25 21:32:26 CST 2019
     */
    CmsAdoptOrgActivity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_org_activity
     *
     * @mbg.generated Sun Aug 25 21:32:26 CST 2019
     */
    int updateByPrimaryKeySelective(CmsAdoptOrgActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_org_activity
     *
     * @mbg.generated Sun Aug 25 21:32:26 CST 2019
     */
    int updateByPrimaryKey(CmsAdoptOrgActivity record);

    /**
     * 获取公益组织活动列表
     *
     * @param orgId
     * @return
     */
    List<CmsAdoptOrgActivity> getAdoptActivityList(String orgId);

    int getActivityCountByOrgIdWithRange(@Param("orgId") String orgId, @Param("fromDay") String fromDay,
			@Param("toDay") String toDay);
}