package com.linkpets.core.dao;

import com.linkpets.core.model.CmsActivityConfig;

public interface CmsActivityConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_config
     *
     * @mbggenerated Wed Mar 27 23:00:04 CST 2019
     */
    int deleteByPrimaryKey(String activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_config
     *
     * @mbggenerated Wed Mar 27 23:00:04 CST 2019
     */
    int insert(CmsActivityConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_config
     *
     * @mbggenerated Wed Mar 27 23:00:04 CST 2019
     */
    int insertSelective(CmsActivityConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_config
     *
     * @mbggenerated Wed Mar 27 23:00:04 CST 2019
     */
    CmsActivityConfig selectByPrimaryKey(String activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_config
     *
     * @mbggenerated Wed Mar 27 23:00:04 CST 2019
     */
    int updateByPrimaryKeySelective(CmsActivityConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_config
     *
     * @mbggenerated Wed Mar 27 23:00:04 CST 2019
     */
    int updateByPrimaryKey(CmsActivityConfig record);
}