package com.linkpets.core.dao;

import com.linkpets.core.model.CmsAdoptPetOrgRel;

public interface CmsAdoptPetOrgRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_pet_org_rel
     *
     * @mbggenerated Fri Aug 16 17:21:11 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_pet_org_rel
     *
     * @mbggenerated Fri Aug 16 17:21:11 CST 2019
     */
    int insert(CmsAdoptPetOrgRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_pet_org_rel
     *
     * @mbggenerated Fri Aug 16 17:21:11 CST 2019
     */
    int insertSelective(CmsAdoptPetOrgRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_pet_org_rel
     *
     * @mbggenerated Fri Aug 16 17:21:11 CST 2019
     */
    CmsAdoptPetOrgRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_pet_org_rel
     *
     * @mbggenerated Fri Aug 16 17:21:11 CST 2019
     */
    int updateByPrimaryKeySelective(CmsAdoptPetOrgRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_pet_org_rel
     *
     * @mbggenerated Fri Aug 16 17:21:11 CST 2019
     */
    int updateByPrimaryKey(CmsAdoptPetOrgRel record);
}