package com.linkpets.core.dao;

import java.util.List;
import java.util.Map;

import com.linkpets.core.model.CmsAdoptAgreement;

public interface CmsAdoptAgreementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_agreement
     *
     * @mbg.generated Sat May 25 15:53:26 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String agreementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_agreement
     *
     * @mbg.generated Sat May 25 15:53:26 GMT+08:00 2019
     */
    int insert(CmsAdoptAgreement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_agreement
     *
     * @mbg.generated Sat May 25 15:53:26 GMT+08:00 2019
     */
    int insertSelective(CmsAdoptAgreement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_agreement
     *
     * @mbg.generated Sat May 25 15:53:26 GMT+08:00 2019
     */
    CmsAdoptAgreement selectByPrimaryKey(String agreementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_agreement
     *
     * @mbg.generated Sat May 25 15:53:26 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(CmsAdoptAgreement record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_agreement
     *
     * @mbg.generated Sat May 25 15:53:26 GMT+08:00 2019
     */
    int updateByPrimaryKey(CmsAdoptAgreement record);

    /**
     * 获取领养协议详情列表
     *
     * @param param
     * @return
     */
    List<Map<String, Object>> getList(Map<String, Object> param);

    /**
     * 通过领养申请Id获取领养协议详情
     *
     * @param applyId
     * @return
     */
    CmsAdoptAgreement getAgreementByApplyId(String applyId);
}