package com.linkpets.core.dao;

import com.linkpets.core.model.CmsAdoptFormid;
import org.apache.ibatis.annotations.Param;

public interface CmsAdoptFormidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_formid
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_formid
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    int insert(CmsAdoptFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_formid
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    int insertSelective(CmsAdoptFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_formid
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    CmsAdoptFormid selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_formid
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    int updateByPrimaryKeySelective(CmsAdoptFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_formid
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    int updateByPrimaryKey(CmsAdoptFormid record);

    /**
     * 获取用户有效formId
     * @param userId
     * @return
     */
    CmsAdoptFormid getValidFormId(String userId);
}