package com.linkpets.core.dao;

import com.linkpets.core.model.CmsAdoptReport;

public interface CmsAdoptReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_report
     *
     * @mbggenerated Sun May 19 15:18:18 CST 2019
     */
    int deleteByPrimaryKey(String reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_report
     *
     * @mbggenerated Sun May 19 15:18:18 CST 2019
     */
    int insert(CmsAdoptReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_report
     *
     * @mbggenerated Sun May 19 15:18:18 CST 2019
     */
    int insertSelective(CmsAdoptReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_report
     *
     * @mbggenerated Sun May 19 15:18:18 CST 2019
     */
    CmsAdoptReport selectByPrimaryKey(String reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_report
     *
     * @mbggenerated Sun May 19 15:18:18 CST 2019
     */
    int updateByPrimaryKeySelective(CmsAdoptReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_report
     *
     * @mbggenerated Sun May 19 15:18:18 CST 2019
     */
    int updateByPrimaryKey(CmsAdoptReport record);
}