package com.linkpets.core.dao;

import com.linkpets.core.model.CmsActivityRegistryInfo;
import org.apache.ibatis.annotations.Param;

public interface CmsActivityRegistryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_registry_info
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    int deleteByPrimaryKey(String infoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_registry_info
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    int insert(CmsActivityRegistryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_registry_info
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    int insertSelective(CmsActivityRegistryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_registry_info
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    CmsActivityRegistryInfo selectByPrimaryKey(String infoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_registry_info
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    int updateByPrimaryKeySelective(CmsActivityRegistryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_registry_info
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    int updateByPrimaryKey(CmsActivityRegistryInfo record);

    /**
     * 获取报名详情
     *
     * @param userId
     * @param activityId
     * @return
     */
    CmsActivityRegistryInfo selectRegistryInfoByUserIdAndActivityId(@Param("userId") String userId, @Param("activityId") String activityId);

}