package com.linkpets.core.dao;

import com.linkpets.core.model.*;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface CmsAdoptOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_org
     *
     * @mbggenerated Fri Aug 16 17:19:34 CST 2019
     */
    int deleteByPrimaryKey(String orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_org
     *
     * @mbggenerated Fri Aug 16 17:19:34 CST 2019
     */
    int insert(CmsAdoptOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_org
     *
     * @mbggenerated Fri Aug 16 17:19:34 CST 2019
     */
    int insertSelective(CmsAdoptOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_org
     *
     * @mbggenerated Fri Aug 16 17:19:34 CST 2019
     */
    CmsAdoptOrg selectByPrimaryKey(String orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_org
     *
     * @mbggenerated Fri Aug 16 17:19:34 CST 2019
     */
    int updateByPrimaryKeySelective(CmsAdoptOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_org
     *
     * @mbggenerated Fri Aug 16 17:19:34 CST 2019
     */
    int updateByPrimaryKey(CmsAdoptOrg record);

    /**
     * 获取公益机构列表
     *
     * @return
     */
    List<CmsAdoptOrg> getAdoptOrgList();

    /**
     * 获取公益机构统计数据
     *
     * @param orgId
     * @param userId
     * @return
     */
    CmsAdoptOrgStatistic getAdoptOrgStatistic(String orgId, String userId);

    /**
     * 获取宠物绑定的公益组织信息
     *
     * @param petId
     * @return
     */
    CmsAdoptPetOrgRel getAdoptPetOrgInfoByPetId(String petId);

    /**
     * 绑定公益组织、宠物
     *
     * @param id
     * @param orgId
     * @param petId
     */
    void crtAdoptOrgPetRel(@Param("id") String id, @Param("orgId") String orgId, @Param("petId") String petId);

    /**
     * 更新公益组织宠物绑定关系
     *
     * @param id
     */
    void uptAdoptOrgPetRel(@Param("id") String id);

    @Update({
            "UPDATE cms_adopt_org ",
            "SET is_valid = 0 ",
            "where org_id = #{orgId}"
    })
    void delOrg(String orgId);

}