package com.linkpets.core.dao;

import com.linkpets.core.model.CmsActivity;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CmsActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    int deleteByPrimaryKey(String activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    int insert(CmsActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    int insertSelective(CmsActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    CmsActivity selectByPrimaryKey(String activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    int updateByPrimaryKeySelective(CmsActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    int updateByPrimaryKey(CmsActivity record);

    /**
     * 根据组织id、活动时间段获取活动列表
     *
     * @param orgId
     * @param startTime
     * @param endTime
     * @param isActive
     * @return
     */
    List<CmsActivity> getActivitiesList(@Param("orgId") String orgId, @Param("startTime") String startTime,
                                        @Param("endTime") String endTime, @Param("isActive") int isActive);
}