package com.linkpets.core.dao;

import com.linkpets.core.model.CmsActivity;

public interface CmsActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    int deleteByPrimaryKey(String activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    int insert(CmsActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    int insertSelective(CmsActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    CmsActivity selectByPrimaryKey(String activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    int updateByPrimaryKeySelective(CmsActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    int updateByPrimaryKey(CmsActivity record);
}