package com.linkpets.core.dao;

import com.linkpets.core.model.CmsAdoptPetMedia;

import java.util.List;

public interface CmsAdoptPetMediaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_pet_media
     *
     * @mbg.generated Wed May 15 21:51:03 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer mediaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_pet_media
     *
     * @mbg.generated Wed May 15 21:51:03 GMT+08:00 2019
     */
    int insert(CmsAdoptPetMedia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_pet_media
     *
     * @mbg.generated Wed May 15 21:51:03 GMT+08:00 2019
     */
    int insertSelective(CmsAdoptPetMedia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_pet_media
     *
     * @mbg.generated Wed May 15 21:51:03 GMT+08:00 2019
     */
    CmsAdoptPetMedia selectByPrimaryKey(Integer mediaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_pet_media
     *
     * @mbg.generated Wed May 15 21:51:03 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(CmsAdoptPetMedia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_pet_media
     *
     * @mbg.generated Wed May 15 21:51:03 GMT+08:00 2019
     */
    int updateByPrimaryKey(CmsAdoptPetMedia record);

    /**
     * 获取宠物相册
     * @param petId
     * @return
     */
    List<CmsAdoptPetMedia> selectByPetId(String petId);
}