package com.linkpets.core.dao;

import com.linkpets.core.model.CmsAdoptFileLog;

public interface CmsAdoptFileLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_file_log
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_file_log
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    int insert(CmsAdoptFileLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_file_log
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    int insertSelective(CmsAdoptFileLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_file_log
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    CmsAdoptFileLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_file_log
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    int updateByPrimaryKeySelective(CmsAdoptFileLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_adopt_file_log
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    int updateByPrimaryKey(CmsAdoptFileLog record);
}