package com.linkpets.core.dao;

import com.linkpets.core.model.CmsBanner;

import java.util.List;

public interface CmsBannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_banner
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    int deleteByPrimaryKey(String bannerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_banner
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    int insert(CmsBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_banner
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    int insertSelective(CmsBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_banner
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    CmsBanner selectByPrimaryKey(String bannerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_banner
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    int updateByPrimaryKeySelective(CmsBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_banner
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    int updateByPrimaryKey(CmsBanner record);

    List<CmsBanner> getBannerList(String activityId,Integer count);
}