package com.linkpets.core.dao;

import com.linkpets.core.model.CmsCoupon;

import java.util.List;

public interface CmsCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    int deleteByPrimaryKey(String couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    int insert(CmsCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    int insertSelective(CmsCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    CmsCoupon selectByPrimaryKey(String couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    int updateByPrimaryKeySelective(CmsCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    int updateByPrimaryKey(CmsCoupon record);

    /**
     * 获取优惠券配置列表
     *
     * @param orgId
     * @return
     */
    List<CmsCoupon> getCouponList(String orgId);
}