package com.linkpets.core.dao;

import com.linkpets.core.model.CmsCouponBatchItem;

public interface CmsCouponBatchItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon_batch_item
     *
     * @mbggenerated Thu Mar 28 01:28:07 CST 2019
     */
    int deleteByPrimaryKey(String couponItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon_batch_item
     *
     * @mbggenerated Thu Mar 28 01:28:07 CST 2019
     */
    int insert(CmsCouponBatchItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon_batch_item
     *
     * @mbggenerated Thu Mar 28 01:28:07 CST 2019
     */
    int insertSelective(CmsCouponBatchItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon_batch_item
     *
     * @mbggenerated Thu Mar 28 01:28:07 CST 2019
     */
    CmsCouponBatchItem selectByPrimaryKey(String couponItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon_batch_item
     *
     * @mbggenerated Thu Mar 28 01:28:07 CST 2019
     */
    int updateByPrimaryKeySelective(CmsCouponBatchItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon_batch_item
     *
     * @mbggenerated Thu Mar 28 01:28:07 CST 2019
     */
    int updateByPrimaryKey(CmsCouponBatchItem record);
}