package com.linkpets.core.dao;

import com.linkpets.core.model.CmsCouponBatch;
import com.linkpets.core.model.CmsCouponBatchItem;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CmsCouponBatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon_batch
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    int deleteByPrimaryKey(String batchNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon_batch
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    int insert(CmsCouponBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon_batch
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    int insertSelective(CmsCouponBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon_batch
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    CmsCouponBatch selectByPrimaryKey(String batchNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon_batch
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    int updateByPrimaryKeySelective(CmsCouponBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon_batch
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    int updateByPrimaryKey(CmsCouponBatch record);

    /**
     * 获取优惠券列表
     *
     * @param couponId
     * @param activityId
     * @param effectiveStart
     * @param effectiveEnd
     * @return
     */
    List<CmsCouponBatch> getCmsCouponBatchList(@Param("couponId") String couponId, @Param("activityId") String activityId, @Param("effectiveStart") String effectiveStart, @Param("effectiveEnd") String effectiveEnd);

    /**
     * 生成优惠券
     *
     * @param items
     * @return
     */
    int insertBatchCouponItem(List<CmsCouponBatchItem> items);
}