package com.linkpets.core.dao;

import com.linkpets.core.model.CmsCouponBatch;

public interface CmsCouponBatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon_batch
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    int deleteByPrimaryKey(String batchNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon_batch
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    int insert(CmsCouponBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon_batch
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    int insertSelective(CmsCouponBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon_batch
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    CmsCouponBatch selectByPrimaryKey(String batchNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon_batch
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    int updateByPrimaryKeySelective(CmsCouponBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_coupon_batch
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    int updateByPrimaryKey(CmsCouponBatch record);
}