package com.linkpets.core.dao;

import com.linkpets.core.model.CmsGroup;
import com.linkpets.core.respEntity.RespGroupInfo;

import java.util.List;

public interface CmsGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_group
     *
     * @mbg.generated Thu Dec 12 13:30:39 CST 2019
     */
    int deleteByPrimaryKey(String groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_group
     *
     * @mbg.generated Thu Dec 12 13:30:39 CST 2019
     */
    int insert(CmsGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_group
     *
     * @mbg.generated Thu Dec 12 13:30:39 CST 2019
     */
    int insertSelective(CmsGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_group
     *
     * @mbg.generated Thu Dec 12 13:30:39 CST 2019
     */
    CmsGroup selectByPrimaryKey(String groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_group
     *
     * @mbg.generated Thu Dec 12 13:30:39 CST 2019
     */
    int updateByPrimaryKeySelective(CmsGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_group
     *
     * @mbg.generated Thu Dec 12 13:30:39 CST 2019
     */
    int updateByPrimaryKey(CmsGroup record);

    /**
     * 获取圈子列表
     *
     * @param groupType
     * @param isActive
     * @param orderBy
     * @return
     */
    List<RespGroupInfo> getGroupList(String groupType, Integer isActive, Integer orderBy);

    /**
     * 获取活动圈子列表
     *
     * @return
     */
    List<CmsGroup> getActivityGroupList();

    /**
     * 获取关注圈子列表
     *
     * @param userId
     * @return
     */
    List<CmsGroup> getFollowedGroupList(String userId);

    /**
     * 获取圈子详情
     *
     * @param groupId
     * @return
     */
    RespGroupInfo getGroup(String groupId, Integer isActive);
}