package com.linkpets.core.dao;

import com.linkpets.core.model.CmsLostPost;

public interface CmsLostPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_lost_post
     *
     * @mbggenerated Thu May 09 21:20:21 CST 2019
     */
    int deleteByPrimaryKey(String postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_lost_post
     *
     * @mbggenerated Thu May 09 21:20:21 CST 2019
     */
    int insert(CmsLostPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_lost_post
     *
     * @mbggenerated Thu May 09 21:20:21 CST 2019
     */
    int insertSelective(CmsLostPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_lost_post
     *
     * @mbggenerated Thu May 09 21:20:21 CST 2019
     */
    CmsLostPost selectByPrimaryKey(String postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_lost_post
     *
     * @mbggenerated Thu May 09 21:20:21 CST 2019
     */
    int updateByPrimaryKeySelective(CmsLostPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_lost_post
     *
     * @mbggenerated Thu May 09 21:20:21 CST 2019
     */
    int updateByPrimaryKey(CmsLostPost record);
}