package com.linkpets.core.dao;

import java.util.List;
import java.util.Map;

import com.linkpets.core.model.CmsUser;
import org.apache.ibatis.annotations.Param;

public interface CmsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbggenerated Mon May 06 14:21:16 CST 2019
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbggenerated Mon May 06 14:21:16 CST 2019
     */
    int insert(CmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbggenerated Mon May 06 14:21:16 CST 2019
     */
    int insertSelective(CmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbggenerated Mon May 06 14:21:16 CST 2019
     */
    CmsUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbggenerated Mon May 06 14:21:16 CST 2019
     */
    int updateByPrimaryKeySelective(CmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbggenerated Mon May 06 14:21:16 CST 2019
     */
    int updateByPrimaryKey(CmsUser record);

    int getAttentionStatus(@Param("userId") String userId,@Param("targetUserId") String targetUserId);

	List<CmsUser> getUserListAttentTo(Map<String, Object> param);

	List<CmsUser> getUserListAttentBy(Map<String, Object> param);

    Map<String,Object> getUserAddition(String userId);
}