package com.linkpets.core.dao;

import java.util.List;
import java.util.Map;

import com.linkpets.core.model.CmsUser;
import org.apache.ibatis.annotations.Param;

public interface CmsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbggenerated Mon May 06 14:21:16 CST 2019
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbggenerated Mon May 06 14:21:16 CST 2019
     */
    int insert(CmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbggenerated Mon May 06 14:21:16 CST 2019
     */
    int insertSelective(CmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbggenerated Mon May 06 14:21:16 CST 2019
     */
    CmsUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbggenerated Mon May 06 14:21:16 CST 2019
     */
    int updateByPrimaryKeySelective(CmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbggenerated Mon May 06 14:21:16 CST 2019
     */
    int updateByPrimaryKey(CmsUser record);

    /**
     * 获取用户是否关注
     *
     * @param userId
     * @param targetUserId
     * @return
     */
    int getAttentionStatus(@Param("userId") String userId, @Param("targetUserId") String targetUserId);

    /**
     * 获取用户关注列表
     *
     * @param param
     * @return
     */
    List<CmsUser> getUserListAttentTo(Map<String, Object> param);

    /**
     * 获取用户被关注列表
     *
     * @param param
     * @return
     */
    List<CmsUser> getUserListAttentBy(Map<String, Object> param);

    /**
     * 获取用户领养统计数据
     *
     * @param userId
     * @return
     */
    Map<String, Object> getUserAddition(String userId);

    /**
     * 获取所有用户数
     *
     * @return
     */
    int getTotalUserCount();

    /**
     * 根据UserId获取用户详情
     *
     * @param userId
     * @return
     */
    CmsUser getUserInfoByUserId(String userId);

    /**
     * 根据unionId获取用户详情
     * @param unionId
     * @return
     */
    CmsUser getUserByUnionId(String unionId);


    String getMaxUserNo(@Param("userIdStart") String userIdStart, @Param("year") String year);

    List<Map<String, Object>> selectUserList(Map<String, Object> map);

    List<Map<String, String>> getUserInfoByUserId(List<String> userIds);
}