package com.linkpets.core.dao;

import com.linkpets.core.model.CommodityBrand;
import org.apache.ibatis.annotations.Mapper;

public interface CommodityBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_brand
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insert(CommodityBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_brand
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insertSelective(CommodityBrand record);
}