package com.linkpets.core.dao;

import com.linkpets.core.model.CommodityType;
import org.apache.ibatis.annotations.Mapper;

public interface CommodityTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insert(CommodityType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insertSelective(CommodityType record);
}