package com.linkpets.core.dao;

import com.linkpets.core.model.MallSpu;
import org.apache.ibatis.annotations.Mapper;

public interface MallSpuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_spu
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int deleteByPrimaryKey(String spuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_spu
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insert(MallSpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_spu
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insertSelective(MallSpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_spu
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    MallSpu selectByPrimaryKey(String spuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_spu
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKeySelective(MallSpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_spu
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKey(MallSpu record);
}