package com.linkpets.core.dao;

import com.linkpets.core.model.OrderMall;

public interface OrderMallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_mall
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_mall
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insert(OrderMall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_mall
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insertSelective(OrderMall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_mall
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    OrderMall selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_mall
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKeySelective(OrderMall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_mall
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKey(OrderMall record);
}