package com.linkpets.core.dao;

import com.linkpets.core.model.PetAlbum;

public interface PetAlbumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_album
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int deleteByPrimaryKey(String albumId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_album
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insert(PetAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_album
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insertSelective(PetAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_album
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    PetAlbum selectByPrimaryKey(String albumId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_album
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKeySelective(PetAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_album
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKey(PetAlbum record);
}