package com.linkpets.core.dao;

import com.linkpets.core.model.PetFollow;

public interface PetFollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_follow
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int deleteByPrimaryKey(String followId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_follow
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insert(PetFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_follow
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insertSelective(PetFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_follow
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    PetFollow selectByPrimaryKey(String followId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_follow
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKeySelective(PetFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_follow
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKey(PetFollow record);
}