package com.linkpets.core.dao;

import com.linkpets.core.model.PetLike;

public interface PetLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_like
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_like
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insert(PetLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_like
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insertSelective(PetLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_like
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    PetLike selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_like
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKeySelective(PetLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_like
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKey(PetLike record);
}