package com.linkpets.core.dao;

import com.linkpets.core.model.PetWeapon;

public interface PetWeaponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_weapon
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int deleteByPrimaryKey(String weaponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_weapon
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insert(PetWeapon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_weapon
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insertSelective(PetWeapon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_weapon
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    PetWeapon selectByPrimaryKey(String weaponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_weapon
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKeySelective(PetWeapon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_weapon
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKey(PetWeapon record);
}