package com.linkpets.core.dao;

import com.linkpets.core.model.PetWeaponConcat;

public interface PetWeaponConcatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_weapon_concat
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_weapon_concat
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insert(PetWeaponConcat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_weapon_concat
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insertSelective(PetWeaponConcat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_weapon_concat
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    PetWeaponConcat selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_weapon_concat
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKeySelective(PetWeaponConcat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_weapon_concat
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKey(PetWeaponConcat record);
}