package com.linkpets.core.dao;

import com.linkpets.core.model.RecordCollect;

public interface RecordCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_collect
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_collect
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insert(RecordCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_collect
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insertSelective(RecordCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_collect
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    RecordCollect selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_collect
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKeySelective(RecordCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_collect
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKey(RecordCollect record);
}