package com.linkpets.core.dao;

import com.linkpets.core.model.RecordLike;

public interface RecordLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_like
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_like
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insert(RecordLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_like
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insertSelective(RecordLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_like
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    RecordLike selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_like
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKeySelective(RecordLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_like
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKey(RecordLike record);
}