package com.linkpets.core.dao;

import com.linkpets.core.model.RecordShare;

public interface RecordShareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_share
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_share
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insert(RecordShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_share
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insertSelective(RecordShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_share
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    RecordShare selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_share
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKeySelective(RecordShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_share
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKey(RecordShare record);
}