package com.linkpets.core.dao;

import com.linkpets.core.model.RecordVisit;

public interface RecordVisitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_visit
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_visit
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insert(RecordVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_visit
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insertSelective(RecordVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_visit
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    RecordVisit selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_visit
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKeySelective(RecordVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_visit
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKey(RecordVisit record);
}