package com.linkpets.core.dao;

import com.linkpets.core.model.SdCatalogList;

import java.util.List;

public interface SdCatalogListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_catalog_list
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_catalog_list
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    int insert(SdCatalogList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_catalog_list
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    int insertSelective(SdCatalogList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_catalog_list
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    SdCatalogList selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_catalog_list
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    int updateByPrimaryKeySelective(SdCatalogList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_catalog_list
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    int updateByPrimaryKey(SdCatalogList record);

    List<SdCatalogList> searchArticle(String search);
}