package com.linkpets.core.dao;

import com.linkpets.core.model.SdCatalog;

import java.util.List;

public interface SdCatalogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_catalog
     *
     * @mbggenerated Wed Aug 21 23:23:28 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_catalog
     *
     * @mbggenerated Wed Aug 21 23:23:28 CST 2019
     */
    int insert(SdCatalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_catalog
     *
     * @mbggenerated Wed Aug 21 23:23:28 CST 2019
     */
    int insertSelective(SdCatalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_catalog
     *
     * @mbggenerated Wed Aug 21 23:23:28 CST 2019
     */
    SdCatalog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_catalog
     *
     * @mbggenerated Wed Aug 21 23:23:28 CST 2019
     */
    int updateByPrimaryKeySelective(SdCatalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_catalog
     *
     * @mbggenerated Wed Aug 21 23:23:28 CST 2019
     */
    int updateByPrimaryKey(SdCatalog record);

    /**
     * 获取目录列表
     *
     * @param type
     * @return
     */
    List<SdCatalog> getCatalogs(String type);
}