package com.linkpets.core.dao;

import com.linkpets.core.model.ShareRecord;

public interface ShareRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_record
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int deleteByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_record
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insert(ShareRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_record
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insertSelective(ShareRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_record
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    ShareRecord selectByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_record
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKeySelective(ShareRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_record
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKey(ShareRecord record);
}