package com.linkpets.core.dao;

import com.linkpets.core.model.SysChain;

public interface SysChainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chain
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    int deleteByPrimaryKey(String chainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chain
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    int insert(SysChain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chain
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    int insertSelective(SysChain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chain
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    SysChain selectByPrimaryKey(String chainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chain
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    int updateByPrimaryKeySelective(SysChain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chain
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    int updateByPrimaryKey(SysChain record);
}