package com.linkpets.core.dao;

import com.linkpets.core.model.SysOrg;

public interface SysOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    int deleteByPrimaryKey(String orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    int insert(SysOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    int insertSelective(SysOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    SysOrg selectByPrimaryKey(String orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    int updateByPrimaryKeySelective(SysOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    int updateByPrimaryKey(SysOrg record);

    /**
     * 根据机构编码获取机构信息
     *
     * @param code
     * @return
     */
    SysOrg getSysOrg(String code);
}