package com.linkpets.core.dao;

import com.linkpets.core.model.SysChain;
import com.linkpets.core.model.SysUser;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Apr 04 20:48:36 CST 2019
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Apr 04 20:48:36 CST 2019
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Apr 04 20:48:36 CST 2019
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Apr 04 20:48:36 CST 2019
     */
    SysUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Apr 04 20:48:36 CST 2019
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Apr 04 20:48:36 CST 2019
     */
    int updateByPrimaryKey(SysUser record);

    /**
     * 根据账号获取系统用户
     *
     * @param userName
     * @return
     */
    SysUser selectByUserName(String userName);

    /**
     * 获取系统账号列表
     *
     * @param orgId
     * @param chainId
     * @return
     */
    List<SysUser> listSysUser(@Param("orgId") String orgId, @Param("chainId") String chainId);

    /**
     * 根据用户名获取账号信息
     *
     * @param userName
     * @return
     */
    SysUser getSysUserByUserName(@Param("userName") String userName);


}