package com.linkpets.core.dao;

import com.linkpets.core.model.UserDonate;

public interface UserDonateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_donate
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_donate
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insert(UserDonate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_donate
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insertSelective(UserDonate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_donate
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    UserDonate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_donate
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKeySelective(UserDonate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_donate
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKey(UserDonate record);
}