package com.linkpets.core.dao;

import com.linkpets.core.model.UserShoppingAddress;

public interface UserShoppingAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_shopping_address
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_shopping_address
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insert(UserShoppingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_shopping_address
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insertSelective(UserShoppingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_shopping_address
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    UserShoppingAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_shopping_address
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKeySelective(UserShoppingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_shopping_address
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKey(UserShoppingAddress record);
}