package com.linkpets.core.dao;

import com.linkpets.core.model.UserWalkHistory;

public interface UserWalkHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_walk_history
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int deleteByPrimaryKey(String historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_walk_history
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insert(UserWalkHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_walk_history
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insertSelective(UserWalkHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_walk_history
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    UserWalkHistory selectByPrimaryKey(String historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_walk_history
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKeySelective(UserWalkHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_walk_history
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKey(UserWalkHistory record);
}