package com.linkpets.core.dao;

import com.linkpets.core.model.UserExploreHistory;

public interface UserExploreHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_explore_history
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int deleteByPrimaryKey(Integer historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_explore_history
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insert(UserExploreHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_explore_history
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insertSelective(UserExploreHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_explore_history
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    UserExploreHistory selectByPrimaryKey(Integer historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_explore_history
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKeySelective(UserExploreHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_explore_history
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(UserExploreHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_explore_history
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKey(UserExploreHistory record);
}