package com.linkpets.core.dao;

import com.linkpets.core.model.UserPaymentLog;

public interface UserPaymentLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment_log
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment_log
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insert(UserPaymentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment_log
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insertSelective(UserPaymentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment_log
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    UserPaymentLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment_log
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKeySelective(UserPaymentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment_log
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKey(UserPaymentLog record);
}