package com.linkpets.core.dao;

import com.linkpets.core.model.UserWalkLocation;

public interface UserWalkLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_walk_location
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_walk_location
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insert(UserWalkLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_walk_location
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insertSelective(UserWalkLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_walk_location
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    UserWalkLocation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_walk_location
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKeySelective(UserWalkLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_walk_location
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKey(UserWalkLocation record);
}