package com.linkpets.core.dao;

import com.linkpets.core.model.UserPet;

public interface UserPetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pet
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pet
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insert(UserPet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pet
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insertSelective(UserPet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pet
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    UserPet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pet
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKeySelective(UserPet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pet
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKey(UserPet record);
}