package com.linkpets.core.dao;

import com.linkpets.core.model.UserLongRecord;

public interface UserLongRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_long_record
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int deleteByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_long_record
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insert(UserLongRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_long_record
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int insertSelective(UserLongRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_long_record
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    UserLongRecord selectByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_long_record
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKeySelective(UserLongRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_long_record
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(UserLongRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_long_record
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    int updateByPrimaryKey(UserLongRecord record);
}