package com.linkpets.core.model;

public class CmsActivityConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_config.activity_id
     *
     * @mbggenerated Wed Mar 27 23:00:04 CST 2019
     */
    private String activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_config.assist_no
     *
     * @mbggenerated Wed Mar 27 23:00:04 CST 2019
     */
    private Integer assistNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_config.draft_present_type
     *
     * @mbggenerated Wed Mar 27 23:00:04 CST 2019
     */
    private String draftPresentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_config.is_active
     *
     * @mbggenerated Wed Mar 27 23:00:04 CST 2019
     */
    private Integer isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_config.is_valid
     *
     * @mbggenerated Wed Mar 27 23:00:04 CST 2019
     */
    private Integer isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_config.activity_id
     *
     * @return the value of cms_activity_config.activity_id
     *
     * @mbggenerated Wed Mar 27 23:00:04 CST 2019
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_config.activity_id
     *
     * @param activityId the value for cms_activity_config.activity_id
     *
     * @mbggenerated Wed Mar 27 23:00:04 CST 2019
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_config.assist_no
     *
     * @return the value of cms_activity_config.assist_no
     *
     * @mbggenerated Wed Mar 27 23:00:04 CST 2019
     */
    public Integer getAssistNo() {
        return assistNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_config.assist_no
     *
     * @param assistNo the value for cms_activity_config.assist_no
     *
     * @mbggenerated Wed Mar 27 23:00:04 CST 2019
     */
    public void setAssistNo(Integer assistNo) {
        this.assistNo = assistNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_config.draft_present_type
     *
     * @return the value of cms_activity_config.draft_present_type
     *
     * @mbggenerated Wed Mar 27 23:00:04 CST 2019
     */
    public String getDraftPresentType() {
        return draftPresentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_config.draft_present_type
     *
     * @param draftPresentType the value for cms_activity_config.draft_present_type
     *
     * @mbggenerated Wed Mar 27 23:00:04 CST 2019
     */
    public void setDraftPresentType(String draftPresentType) {
        this.draftPresentType = draftPresentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_config.is_active
     *
     * @return the value of cms_activity_config.is_active
     *
     * @mbggenerated Wed Mar 27 23:00:04 CST 2019
     */
    public Integer getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_config.is_active
     *
     * @param isActive the value for cms_activity_config.is_active
     *
     * @mbggenerated Wed Mar 27 23:00:04 CST 2019
     */
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_config.is_valid
     *
     * @return the value of cms_activity_config.is_valid
     *
     * @mbggenerated Wed Mar 27 23:00:04 CST 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_config.is_valid
     *
     * @param isValid the value for cms_activity_config.is_valid
     *
     * @mbggenerated Wed Mar 27 23:00:04 CST 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
}