package com.linkpets.core.model;

public class CmsAdoptPetMedia {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_pet_media.media_id
     *
     * @mbg.generated Wed May 15 21:51:03 GMT+08:00 2019
     */
    private Integer mediaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_pet_media.pet_id
     *
     * @mbg.generated Wed May 15 21:51:03 GMT+08:00 2019
     */
    private String petId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_pet_media.media_type
     *
     * @mbg.generated Wed May 15 21:51:03 GMT+08:00 2019
     */
    private String mediaType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_pet_media.media_path
     *
     * @mbg.generated Wed May 15 21:51:03 GMT+08:00 2019
     */
    private String mediaPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_pet_media.is_valid
     *
     * @mbg.generated Wed May 15 21:51:03 GMT+08:00 2019
     */
    private String isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_pet_media.media_id
     *
     * @return the value of cms_adopt_pet_media.media_id
     *
     * @mbg.generated Wed May 15 21:51:03 GMT+08:00 2019
     */
    public Integer getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_pet_media.media_id
     *
     * @param mediaId the value for cms_adopt_pet_media.media_id
     *
     * @mbg.generated Wed May 15 21:51:03 GMT+08:00 2019
     */
    public void setMediaId(Integer mediaId) {
        this.mediaId = mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_pet_media.pet_id
     *
     * @return the value of cms_adopt_pet_media.pet_id
     *
     * @mbg.generated Wed May 15 21:51:03 GMT+08:00 2019
     */
    public String getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_pet_media.pet_id
     *
     * @param petId the value for cms_adopt_pet_media.pet_id
     *
     * @mbg.generated Wed May 15 21:51:03 GMT+08:00 2019
     */
    public void setPetId(String petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_pet_media.media_type
     *
     * @return the value of cms_adopt_pet_media.media_type
     *
     * @mbg.generated Wed May 15 21:51:03 GMT+08:00 2019
     */
    public String getMediaType() {
        return mediaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_pet_media.media_type
     *
     * @param mediaType the value for cms_adopt_pet_media.media_type
     *
     * @mbg.generated Wed May 15 21:51:03 GMT+08:00 2019
     */
    public void setMediaType(String mediaType) {
        this.mediaType = mediaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_pet_media.media_path
     *
     * @return the value of cms_adopt_pet_media.media_path
     *
     * @mbg.generated Wed May 15 21:51:03 GMT+08:00 2019
     */
    public String getMediaPath() {
        return mediaPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_pet_media.media_path
     *
     * @param mediaPath the value for cms_adopt_pet_media.media_path
     *
     * @mbg.generated Wed May 15 21:51:03 GMT+08:00 2019
     */
    public void setMediaPath(String mediaPath) {
        this.mediaPath = mediaPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_pet_media.is_valid
     *
     * @return the value of cms_adopt_pet_media.is_valid
     *
     * @mbg.generated Wed May 15 21:51:03 GMT+08:00 2019
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_pet_media.is_valid
     *
     * @param isValid the value for cms_adopt_pet_media.is_valid
     *
     * @mbg.generated Wed May 15 21:51:03 GMT+08:00 2019
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }
}