package com.linkpets.core.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

import static com.linkpets.util.DateUtils.getFormatDateTime;

public class CmsActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity.activity_id
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    private String activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity.activity_name
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity.introduction
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity.start_time
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity.end_time
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity.org_id
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity.create_time
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity.is_active
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    private Integer isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity.is_valid
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    private Integer isValid;

    public CmsActivity(){}

    public CmsActivity(String activityId, String activityName, String introduction, Date startTime, Date endTime, String orgId, Date createTime, Integer isActive, Integer isValid) {
        this.activityId = activityId;
        this.activityName = activityName;
        this.introduction = introduction;
        this.startTime = startTime;
        this.endTime = endTime;
        this.orgId = orgId;
        this.createTime = createTime;
        this.isActive = isActive;
        this.isValid = isValid;
    }

    public CmsActivity(String activityId, String activityName, String introduction, String startTime, String endTime, String orgId, Date createTime) {
        this.activityId = activityId;
        this.activityName = activityName;
        this.introduction = introduction;
        this.startTime = getFormatDateTime(startTime);
        this.endTime = getFormatDateTime(endTime);
        this.orgId = orgId;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity.activity_id
     *
     * @return the value of cms_activity.activity_id
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity.activity_id
     *
     * @param activityId the value for cms_activity.activity_id
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity.activity_name
     *
     * @return the value of cms_activity.activity_name
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity.activity_name
     *
     * @param activityName the value for cms_activity.activity_name
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity.introduction
     *
     * @return the value of cms_activity.introduction
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity.introduction
     *
     * @param introduction the value for cms_activity.introduction
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity.start_time
     *
     * @return the value of cms_activity.start_time
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity.start_time
     *
     * @param startTime the value for cms_activity.start_time
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity.end_time
     *
     * @return the value of cms_activity.end_time
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity.end_time
     *
     * @param endTime the value for cms_activity.end_time
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity.org_id
     *
     * @return the value of cms_activity.org_id
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity.org_id
     *
     * @param orgId the value for cms_activity.org_id
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity.create_time
     *
     * @return the value of cms_activity.create_time
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity.create_time
     *
     * @param createTime the value for cms_activity.create_time
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity.is_active
     *
     * @return the value of cms_activity.is_active
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public Integer getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity.is_active
     *
     * @param isActive the value for cms_activity.is_active
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity.is_valid
     *
     * @return the value of cms_activity.is_valid
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity.is_valid
     *
     * @param isValid the value for cms_activity.is_valid
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
}