package com.linkpets.core.model;

import com.alibaba.fastjson.annotation.JSONField;

import java.util.Date;

public class CmsAdoptGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_group.group_id
     *
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_group.group_type
     *
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    private String groupType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_group.group_name
     *
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_group.group_info
     *
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    private String groupInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_group.group_portrait
     *
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    private String groupPortrait;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_group.group_banner
     *
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    private String groupBanner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_group.sort
     *
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_group.is_valid
     *
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_group.create_date
     *
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_group.group_id
     *
     * @return the value of cms_adopt_group.group_id
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_group.group_id
     *
     * @param groupId the value for cms_adopt_group.group_id
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_group.group_type
     *
     * @return the value of cms_adopt_group.group_type
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    public String getGroupType() {
        return groupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_group.group_type
     *
     * @param groupType the value for cms_adopt_group.group_type
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    public void setGroupType(String groupType) {
        this.groupType = groupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_group.group_name
     *
     * @return the value of cms_adopt_group.group_name
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_group.group_name
     *
     * @param groupName the value for cms_adopt_group.group_name
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_group.group_info
     *
     * @return the value of cms_adopt_group.group_info
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    public String getGroupInfo() {
        return groupInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_group.group_info
     *
     * @param groupInfo the value for cms_adopt_group.group_info
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    public void setGroupInfo(String groupInfo) {
        this.groupInfo = groupInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_group.group_portrait
     *
     * @return the value of cms_adopt_group.group_portrait
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    public String getGroupPortrait() {
        return groupPortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_group.group_portrait
     *
     * @param groupPortrait the value for cms_adopt_group.group_portrait
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    public void setGroupPortrait(String groupPortrait) {
        this.groupPortrait = groupPortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_group.group_banner
     *
     * @return the value of cms_adopt_group.group_banner
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    public String getGroupBanner() {
        return groupBanner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_group.group_banner
     *
     * @param groupBanner the value for cms_adopt_group.group_banner
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    public void setGroupBanner(String groupBanner) {
        this.groupBanner = groupBanner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_group.sort
     *
     * @return the value of cms_adopt_group.sort
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_group.sort
     *
     * @param sort the value for cms_adopt_group.sort
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_group.is_valid
     *
     * @return the value of cms_adopt_group.is_valid
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_group.is_valid
     *
     * @param isValid the value for cms_adopt_group.is_valid
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_group.create_date
     *
     * @return the value of cms_adopt_group.create_date
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_group.create_date
     *
     * @param createDate the value for cms_adopt_group.create_date
     * @mbg.generated Thu Dec 12 13:42:44 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}