package com.linkpets.core.model;

import java.util.Date;

public class CmsAdoptReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_report.report_id
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    private String reportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_report.pet_id
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    private String petId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_report.report_type
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    private String reportType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_report.report_status
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    private String reportStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_report.memo
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_report.report_user_id
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    private String reportUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_report.create_date
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_report.is_valid
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    private Integer isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_report.report_id
     *
     * @return the value of cms_adopt_report.report_id
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    public String getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_report.report_id
     *
     * @param reportId the value for cms_adopt_report.report_id
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    public void setReportId(String reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_report.pet_id
     *
     * @return the value of cms_adopt_report.pet_id
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    public String getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_report.pet_id
     *
     * @param petId the value for cms_adopt_report.pet_id
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    public void setPetId(String petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_report.report_type
     *
     * @return the value of cms_adopt_report.report_type
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    public String getReportType() {
        return reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_report.report_type
     *
     * @param reportType the value for cms_adopt_report.report_type
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    public void setReportType(String reportType) {
        this.reportType = reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_report.report_status
     *
     * @return the value of cms_adopt_report.report_status
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    public String getReportStatus() {
        return reportStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_report.report_status
     *
     * @param reportStatus the value for cms_adopt_report.report_status
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    public void setReportStatus(String reportStatus) {
        this.reportStatus = reportStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_report.memo
     *
     * @return the value of cms_adopt_report.memo
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_report.memo
     *
     * @param memo the value for cms_adopt_report.memo
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_report.report_user_id
     *
     * @return the value of cms_adopt_report.report_user_id
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    public String getReportUserId() {
        return reportUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_report.report_user_id
     *
     * @param reportUserId the value for cms_adopt_report.report_user_id
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    public void setReportUserId(String reportUserId) {
        this.reportUserId = reportUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_report.create_date
     *
     * @return the value of cms_adopt_report.create_date
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_report.create_date
     *
     * @param createDate the value for cms_adopt_report.create_date
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_report.is_valid
     *
     * @return the value of cms_adopt_report.is_valid
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_report.is_valid
     *
     * @param isValid the value for cms_adopt_r∞eport.is_valid
     *
     * @mbggenerated Sun May 19 15:35:33 CST 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
}