package com.linkpets.core.model;

import java.util.Date;

public class CmsAdoptPetOrgRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_pet_org_rel.id
     *
     * @mbggenerated Fri Aug 16 17:21:11 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_pet_org_rel.org_id
     *
     * @mbggenerated Fri Aug 16 17:21:11 CST 2019
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_pet_org_rel.pet_id
     *
     * @mbggenerated Fri Aug 16 17:21:11 CST 2019
     */
    private String petId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_pet_org_rel.is_valid
     *
     * @mbggenerated Fri Aug 16 17:21:11 CST 2019
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_pet_org_rel.create_date
     *
     * @mbggenerated Fri Aug 16 17:21:11 CST 2019
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_pet_org_rel.id
     *
     * @return the value of cms_adopt_pet_org_rel.id
     *
     * @mbggenerated Fri Aug 16 17:21:11 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_pet_org_rel.id
     *
     * @param id the value for cms_adopt_pet_org_rel.id
     *
     * @mbggenerated Fri Aug 16 17:21:11 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_pet_org_rel.org_id
     *
     * @return the value of cms_adopt_pet_org_rel.org_id
     *
     * @mbggenerated Fri Aug 16 17:21:11 CST 2019
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_pet_org_rel.org_id
     *
     * @param orgId the value for cms_adopt_pet_org_rel.org_id
     *
     * @mbggenerated Fri Aug 16 17:21:11 CST 2019
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_pet_org_rel.pet_id
     *
     * @return the value of cms_adopt_pet_org_rel.pet_id
     *
     * @mbggenerated Fri Aug 16 17:21:11 CST 2019
     */
    public String getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_pet_org_rel.pet_id
     *
     * @param petId the value for cms_adopt_pet_org_rel.pet_id
     *
     * @mbggenerated Fri Aug 16 17:21:11 CST 2019
     */
    public void setPetId(String petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_pet_org_rel.is_valid
     *
     * @return the value of cms_adopt_pet_org_rel.is_valid
     *
     * @mbggenerated Fri Aug 16 17:21:11 CST 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_pet_org_rel.is_valid
     *
     * @param isValid the value for cms_adopt_pet_org_rel.is_valid
     *
     * @mbggenerated Fri Aug 16 17:21:11 CST 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_pet_org_rel.create_date
     *
     * @return the value of cms_adopt_pet_org_rel.create_date
     *
     * @mbggenerated Fri Aug 16 17:21:11 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_pet_org_rel.create_date
     *
     * @param createDate the value for cms_adopt_pet_org_rel.create_date
     *
     * @mbggenerated Fri Aug 16 17:21:11 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}