package com.linkpets.core.model;

import java.util.Date;

public class CmsActivityAssistance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_assistance.assist_id
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    private String assistId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_assistance.activity_id
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    private String activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_assistance.user_id
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_assistance.assist_type
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    private Integer assistType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_assistance.assist_user_id
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    private String assistUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_assistance.create_time
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_assistance.is_valid
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_assistance.assist_order
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    private Integer assistOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_assistance.assist_id
     *
     * @return the value of cms_activity_assistance.assist_id
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    public String getAssistId() {
        return assistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_assistance.assist_id
     *
     * @param assistId the value for cms_activity_assistance.assist_id
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    public void setAssistId(String assistId) {
        this.assistId = assistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_assistance.activity_id
     *
     * @return the value of cms_activity_assistance.activity_id
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_assistance.activity_id
     *
     * @param activityId the value for cms_activity_assistance.activity_id
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_assistance.user_id
     *
     * @return the value of cms_activity_assistance.user_id
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_assistance.user_id
     *
     * @param userId the value for cms_activity_assistance.user_id
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_assistance.assist_type
     *
     * @return the value of cms_activity_assistance.assist_type
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    public Integer getAssistType() {
        return assistType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_assistance.assist_type
     *
     * @param assistType the value for cms_activity_assistance.assist_type
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    public void setAssistType(Integer assistType) {
        this.assistType = assistType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_assistance.assist_user_id
     *
     * @return the value of cms_activity_assistance.assist_user_id
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    public String getAssistUserId() {
        return assistUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_assistance.assist_user_id
     *
     * @param assistUserId the value for cms_activity_assistance.assist_user_id
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    public void setAssistUserId(String assistUserId) {
        this.assistUserId = assistUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_assistance.create_time
     *
     * @return the value of cms_activity_assistance.create_time
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_assistance.create_time
     *
     * @param createTime the value for cms_activity_assistance.create_time
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_assistance.is_valid
     *
     * @return the value of cms_activity_assistance.is_valid
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_assistance.is_valid
     *
     * @param isValid the value for cms_activity_assistance.is_valid
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_assistance.assist_order
     *
     * @return the value of cms_activity_assistance.assist_order
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    public Integer getAssistOrder() {
        return assistOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_assistance.assist_order
     *
     * @param assistOrder the value for cms_activity_assistance.assist_order
     *
     * @mbggenerated Tue Mar 26 15:16:53 CST 2019
     */
    public void setAssistOrder(Integer assistOrder) {
        this.assistOrder = assistOrder;
    }
}