package com.linkpets.core.model;

import java.util.Date;

public class CmsAdoptFileLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_file_log.id
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_file_log.file_size
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    private Integer fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_file_log.file_name
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_file_log.user_id
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_file_log.oss_space
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    private String ossSpace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_file_log.create_time
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_file_log.id
     *
     * @return the value of cms_adopt_file_log.id
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_file_log.id
     *
     * @param id the value for cms_adopt_file_log.id
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_file_log.file_size
     *
     * @return the value of cms_adopt_file_log.file_size
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    public Integer getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_file_log.file_size
     *
     * @param fileSize the value for cms_adopt_file_log.file_size
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_file_log.file_name
     *
     * @return the value of cms_adopt_file_log.file_name
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_file_log.file_name
     *
     * @param fileName the value for cms_adopt_file_log.file_name
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_file_log.user_id
     *
     * @return the value of cms_adopt_file_log.user_id
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_file_log.user_id
     *
     * @param userId the value for cms_adopt_file_log.user_id
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_file_log.oss_space
     *
     * @return the value of cms_adopt_file_log.oss_space
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    public String getOssSpace() {
        return ossSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_file_log.oss_space
     *
     * @param ossSpace the value for cms_adopt_file_log.oss_space
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    public void setOssSpace(String ossSpace) {
        this.ossSpace = ossSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_file_log.create_time
     *
     * @return the value of cms_adopt_file_log.create_time
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_file_log.create_time
     *
     * @param createTime the value for cms_adopt_file_log.create_time
     *
     * @mbggenerated Tue Jun 04 09:30:51 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}