package com.linkpets.core.model;

import java.util.Date;

public class CmsAdoptFormid {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_formid.id
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_formid.form_id
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    private String formId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_formid.user_id
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_formid.is_valid
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_formid.create_time
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_formid.expire_time
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    private Date expireTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_formid.id
     *
     * @return the value of cms_adopt_formid.id
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_formid.id
     *
     * @param id the value for cms_adopt_formid.id
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_formid.form_id
     *
     * @return the value of cms_adopt_formid.form_id
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    public String getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_formid.form_id
     *
     * @param formId the value for cms_adopt_formid.form_id
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    public void setFormId(String formId) {
        this.formId = formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_formid.user_id
     *
     * @return the value of cms_adopt_formid.user_id
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_formid.user_id
     *
     * @param userId the value for cms_adopt_formid.user_id
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_formid.is_valid
     *
     * @return the value of cms_adopt_formid.is_valid
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_formid.is_valid
     *
     * @param isValid the value for cms_adopt_formid.is_valid
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_formid.create_time
     *
     * @return the value of cms_adopt_formid.create_time
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_formid.create_time
     *
     * @param createTime the value for cms_adopt_formid.create_time
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_formid.expire_time
     *
     * @return the value of cms_adopt_formid.expire_time
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_formid.expire_time
     *
     * @param expireTime the value for cms_adopt_formid.expire_time
     *
     * @mbggenerated Mon Jul 08 15:31:24 CST 2019
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }
}