package com.linkpets.core.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import java.util.Date;
import java.util.List;

@Data
public class CmsAdoptPet {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adopt_pet.pet_id
	 * @mbg.generated  Sat May 18 14:37:24 GMT+08:00 2019
	 */
	private String petId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adopt_pet.pet_name
	 * @mbg.generated  Sat May 18 14:37:24 GMT+08:00 2019
	 */
	private String petName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adopt_pet.pet_age
	 * @mbg.generated  Sat May 18 14:37:24 GMT+08:00 2019
	 */
	private String petAge;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adopt_pet.pet_type
	 * @mbg.generated  Sat May 18 14:37:24 GMT+08:00 2019
	 */
	private String petType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adopt_pet.pet_sex
	 * @mbg.generated  Sat May 18 14:37:24 GMT+08:00 2019
	 */
	private String petSex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adopt_pet.pet_sterilization
	 * @mbg.generated  Sat May 18 14:37:24 GMT+08:00 2019
	 */
	private String petSterilization;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adopt_pet.pet_vaccine
	 * @mbg.generated  Sat May 18 14:37:24 GMT+08:00 2019
	 */
	private String petVaccine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adopt_pet.pet_parasite
	 * @mbg.generated  Sat May 18 14:37:24 GMT+08:00 2019
	 */
	private String petParasite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adopt_pet.pet_from
	 * @mbg.generated  Sat May 18 14:37:24 GMT+08:00 2019
	 */
	private String petFrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adopt_pet.pet_somatotype
	 * @mbg.generated  Sat May 18 14:37:24 GMT+08:00 2019
	 */
	private String petSomatotype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adopt_pet.pet_hair
	 * @mbg.generated  Sat May 18 14:37:24 GMT+08:00 2019
	 */
	private String petHair;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adopt_pet.pet_characteristic
	 * @mbg.generated  Sat May 18 14:37:24 GMT+08:00 2019
	 */
	private String petCharacteristic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adopt_pet.adopt_requirements
	 * @mbg.generated  Sat May 18 14:37:24 GMT+08:00 2019
	 */
	private String adoptRequirements;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adopt_pet.address
	 * @mbg.generated  Sat May 18 14:37:24 GMT+08:00 2019
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adopt_pet.wx_id
	 * @mbg.generated  Sat May 18 14:37:24 GMT+08:00 2019
	 */
	private String wxId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adopt_pet.mobile_phone
	 * @mbg.generated  Sat May 18 14:37:24 GMT+08:00 2019
	 */
	private String mobilePhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adopt_pet.adopt_status
	 * @mbg.generated  Sat May 18 14:37:24 GMT+08:00 2019
	 */
	private String adoptStatus;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column cms_adopt_pet.memo
	 *
	 * @mbggenerated Sun May 19 12:29:03 CST 2019
	 */
	private String memo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adopt_pet.create_by
	 * @mbg.generated  Sat May 18 14:37:24 GMT+08:00 2019
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adopt_pet.create_date
	 * @mbg.generated  Sat May 18 14:37:24 GMT+08:00 2019
	 */
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adopt_pet.is_valid
	 * @mbg.generated  Sat May 18 14:37:24 GMT+08:00 2019
	 */
	private String isValid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_adopt_pet.story
	 * @mbg.generated  Sat May 18 14:37:24 GMT+08:00 2019
	 */
	private String story;

	private List<CmsAdoptPetMedia> mediaList;

	private boolean collected;



}