package com.linkpets.core.model;

import java.util.Date;

public class CmsAdoptAttention {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_attention.pk_id
     *
     * @mbg.generated Tue May 21 21:19:55 GMT+08:00 2019
     */
    private Integer pkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_attention.user_id
     *
     * @mbg.generated Tue May 21 21:19:55 GMT+08:00 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_attention.attent_by
     *
     * @mbg.generated Tue May 21 21:19:55 GMT+08:00 2019
     */
    private String attentBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_attention.attent_time
     *
     * @mbg.generated Tue May 21 21:19:55 GMT+08:00 2019
     */
    private Date attentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_attention.is_valid
     *
     * @mbg.generated Tue May 21 21:19:55 GMT+08:00 2019
     */
    private String isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_attention.pk_id
     *
     * @return the value of cms_adopt_attention.pk_id
     *
     * @mbg.generated Tue May 21 21:19:55 GMT+08:00 2019
     */
    public Integer getPkId() {
        return pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_attention.pk_id
     *
     * @param pkId the value for cms_adopt_attention.pk_id
     *
     * @mbg.generated Tue May 21 21:19:55 GMT+08:00 2019
     */
    public void setPkId(Integer pkId) {
        this.pkId = pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_attention.user_id
     *
     * @return the value of cms_adopt_attention.user_id
     *
     * @mbg.generated Tue May 21 21:19:55 GMT+08:00 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_attention.user_id
     *
     * @param userId the value for cms_adopt_attention.user_id
     *
     * @mbg.generated Tue May 21 21:19:55 GMT+08:00 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_attention.attent_by
     *
     * @return the value of cms_adopt_attention.attent_by
     *
     * @mbg.generated Tue May 21 21:19:55 GMT+08:00 2019
     */
    public String getAttentBy() {
        return attentBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_attention.attent_by
     *
     * @param attentBy the value for cms_adopt_attention.attent_by
     *
     * @mbg.generated Tue May 21 21:19:55 GMT+08:00 2019
     */
    public void setAttentBy(String attentBy) {
        this.attentBy = attentBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_attention.attent_time
     *
     * @return the value of cms_adopt_attention.attent_time
     *
     * @mbg.generated Tue May 21 21:19:55 GMT+08:00 2019
     */
    public Date getAttentTime() {
        return attentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_attention.attent_time
     *
     * @param attentTime the value for cms_adopt_attention.attent_time
     *
     * @mbg.generated Tue May 21 21:19:55 GMT+08:00 2019
     */
    public void setAttentTime(Date attentTime) {
        this.attentTime = attentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_attention.is_valid
     *
     * @return the value of cms_adopt_attention.is_valid
     *
     * @mbg.generated Tue May 21 21:19:55 GMT+08:00 2019
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_attention.is_valid
     *
     * @param isValid the value for cms_adopt_attention.is_valid
     *
     * @mbg.generated Tue May 21 21:19:55 GMT+08:00 2019
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }
}