package com.linkpets.core.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class CmsAdoptMsg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_msg.msg_id
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    private Integer msgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_msg.msg_title
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    private String msgTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_msg.msg_content
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    private String msgContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_msg.msg_type
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    private Integer msgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_msg.sender
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    private String sender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_msg.receiver
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_msg.is_read
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    private Integer isRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_msg.pet_id
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    private String petId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_msg.is_valid
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_msg.create_time
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date createTime;

    private String dateBefore;

    private int unreadNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_msg.msg_id
     *
     * @return the value of cms_adopt_msg.msg_id
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    public Integer getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_msg.msg_id
     *
     * @param msgId the value for cms_adopt_msg.msg_id
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    public void setMsgId(Integer msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_msg.msg_title
     *
     * @return the value of cms_adopt_msg.msg_title
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    public String getMsgTitle() {
        return msgTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_msg.msg_title
     *
     * @param msgTitle the value for cms_adopt_msg.msg_title
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    public void setMsgTitle(String msgTitle) {
        this.msgTitle = msgTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_msg.msg_content
     *
     * @return the value of cms_adopt_msg.msg_content
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    public String getMsgContent() {
        return msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_msg.msg_content
     *
     * @param msgContent the value for cms_adopt_msg.msg_content
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_msg.msg_type
     *
     * @return the value of cms_adopt_msg.msg_type
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    public Integer getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_msg.msg_type
     *
     * @param msgType the value for cms_adopt_msg.msg_type
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    public void setMsgType(Integer msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_msg.sender
     *
     * @return the value of cms_adopt_msg.sender
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_msg.sender
     *
     * @param sender the value for cms_adopt_msg.sender
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    public void setSender(String sender) {
        this.sender = sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_msg.receiver
     *
     * @return the value of cms_adopt_msg.receiver
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_msg.receiver
     *
     * @param receiver the value for cms_adopt_msg.receiver
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_msg.is_read
     *
     * @return the value of cms_adopt_msg.is_read
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    public Integer getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_msg.is_read
     *
     * @param isRead the value for cms_adopt_msg.is_read
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    public void setIsRead(Integer isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_msg.pet_id
     *
     * @return the value of cms_adopt_msg.pet_id
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    public String getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_msg.pet_id
     *
     * @param petId the value for cms_adopt_msg.pet_id
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    public void setPetId(String petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_msg.is_valid
     *
     * @return the value of cms_adopt_msg.is_valid
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_msg.is_valid
     *
     * @param isValid the value for cms_adopt_msg.is_valid
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_msg.create_time
     *
     * @return the value of cms_adopt_msg.create_time
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_msg.create_time
     *
     * @param createTime the value for cms_adopt_msg.create_time
     *
     * @mbggenerated Tue May 28 11:52:13 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }


    public String getDateBefore() {
        return dateBefore;
    }

    public void setDateBefore(String dateBefore) {
        this.dateBefore = dateBefore;
    }

    public int getUnreadNumber() {
        return unreadNumber;
    }

    public void setUnreadNumber(int unreadNumber) {
        this.unreadNumber = unreadNumber;
    }
}