package com.linkpets.core.model;

import java.util.Date;

public class CmsAdoptCertification {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_certification.id
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_certification.user_id
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_certification.id_card
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_certification.image_front
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    private String imageFront;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_certification.image_back
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    private String imageBack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_certification.status
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_certification.memo
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_certification.is_valid
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_adopt_certification.create_date
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_certification.id
     *
     * @return the value of cms_adopt_certification.id
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_certification.id
     *
     * @param id the value for cms_adopt_certification.id
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_certification.user_id
     *
     * @return the value of cms_adopt_certification.user_id
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_certification.user_id
     *
     * @param userId the value for cms_adopt_certification.user_id
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_certification.id_card
     *
     * @return the value of cms_adopt_certification.id_card
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_certification.id_card
     *
     * @param idCard the value for cms_adopt_certification.id_card
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_certification.image_front
     *
     * @return the value of cms_adopt_certification.image_front
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    public String getImageFront() {
        return imageFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_certification.image_front
     *
     * @param imageFront the value for cms_adopt_certification.image_front
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    public void setImageFront(String imageFront) {
        this.imageFront = imageFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_certification.image_back
     *
     * @return the value of cms_adopt_certification.image_back
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    public String getImageBack() {
        return imageBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_certification.image_back
     *
     * @param imageBack the value for cms_adopt_certification.image_back
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    public void setImageBack(String imageBack) {
        this.imageBack = imageBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_certification.status
     *
     * @return the value of cms_adopt_certification.status
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_certification.status
     *
     * @param status the value for cms_adopt_certification.status
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_certification.memo
     *
     * @return the value of cms_adopt_certification.memo
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_certification.memo
     *
     * @param memo the value for cms_adopt_certification.memo
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_certification.is_valid
     *
     * @return the value of cms_adopt_certification.is_valid
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_certification.is_valid
     *
     * @param isValid the value for cms_adopt_certification.is_valid
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_adopt_certification.create_date
     *
     * @return the value of cms_adopt_certification.create_date
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_adopt_certification.create_date
     *
     * @param createDate the value for cms_adopt_certification.create_date
     *
     * @mbggenerated Wed Jun 19 17:02:57 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}