package com.linkpets.core.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class CmsActivityRegistry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_registry.registry_id
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    private String registryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_registry.activity_id
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    private String activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_registry.user_id
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_registry.registry_type
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    private Integer registryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_registry.create_time
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_registry.is_valid
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    private Integer isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_registry.registry_id
     *
     * @return the value of cms_activity_registry.registry_id
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public String getRegistryId() {
        return registryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_registry.registry_id
     *
     * @param registryId the value for cms_activity_registry.registry_id
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public void setRegistryId(String registryId) {
        this.registryId = registryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_registry.activity_id
     *
     * @return the value of cms_activity_registry.activity_id
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_registry.activity_id
     *
     * @param activityId the value for cms_activity_registry.activity_id
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_registry.user_id
     *
     * @return the value of cms_activity_registry.user_id
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_registry.user_id
     *
     * @param userId the value for cms_activity_registry.user_id
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_registry.registry_type
     *
     * @return the value of cms_activity_registry.registry_type
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public Integer getRegistryType() {
        return registryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_registry.registry_type
     *
     * @param registryType the value for cms_activity_registry.registry_type
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public void setRegistryType(Integer registryType) {
        this.registryType = registryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_registry.create_time
     *
     * @return the value of cms_activity_registry.create_time
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_registry.create_time
     *
     * @param createTime the value for cms_activity_registry.create_time
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_registry.is_valid
     *
     * @return the value of cms_activity_registry.is_valid
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_registry.is_valid
     *
     * @param isValid the value for cms_activity_registry.is_valid
     *
     * @mbggenerated Sat Mar 23 02:03:01 CST 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
}