package com.linkpets.core.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class CmsActivityRegistryInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_registry_info.info_id
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    private String infoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_registry_info.register_name
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    private String registerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_registry_info.register_wx
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    private String registerWx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_registry_info.register_phone
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    private String registerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_registry_info.info_content_first
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    private String infoContentFirst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_registry_info.info_content_second
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    private String infoContentSecond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_registry_info.info_content_third
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    private String infoContentThird;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_registry_info.info_content_forth
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    private String infoContentForth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_registry_info.activity_id
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    private String activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_registry_info.user_id
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_registry_info.state
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_registry_info.is_valid
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_registry_info.create_time
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_registry_info.info_id
     *
     * @return the value of cms_activity_registry_info.info_id
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public String getInfoId() {
        return infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_registry_info.info_id
     *
     * @param infoId the value for cms_activity_registry_info.info_id
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public void setInfoId(String infoId) {
        this.infoId = infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_registry_info.register_name
     *
     * @return the value of cms_activity_registry_info.register_name
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public String getRegisterName() {
        return registerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_registry_info.register_name
     *
     * @param registerName the value for cms_activity_registry_info.register_name
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public void setRegisterName(String registerName) {
        this.registerName = registerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_registry_info.register_wx
     *
     * @return the value of cms_activity_registry_info.register_wx
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public String getRegisterWx() {
        return registerWx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_registry_info.register_wx
     *
     * @param registerWx the value for cms_activity_registry_info.register_wx
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public void setRegisterWx(String registerWx) {
        this.registerWx = registerWx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_registry_info.register_phone
     *
     * @return the value of cms_activity_registry_info.register_phone
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public String getRegisterPhone() {
        return registerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_registry_info.register_phone
     *
     * @param registerPhone the value for cms_activity_registry_info.register_phone
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public void setRegisterPhone(String registerPhone) {
        this.registerPhone = registerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_registry_info.info_content_first
     *
     * @return the value of cms_activity_registry_info.info_content_first
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public String getInfoContentFirst() {
        return infoContentFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_registry_info.info_content_first
     *
     * @param infoContentFirst the value for cms_activity_registry_info.info_content_first
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public void setInfoContentFirst(String infoContentFirst) {
        this.infoContentFirst = infoContentFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_registry_info.info_content_second
     *
     * @return the value of cms_activity_registry_info.info_content_second
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public String getInfoContentSecond() {
        return infoContentSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_registry_info.info_content_second
     *
     * @param infoContentSecond the value for cms_activity_registry_info.info_content_second
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public void setInfoContentSecond(String infoContentSecond) {
        this.infoContentSecond = infoContentSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_registry_info.info_content_third
     *
     * @return the value of cms_activity_registry_info.info_content_third
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public String getInfoContentThird() {
        return infoContentThird;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_registry_info.info_content_third
     *
     * @param infoContentThird the value for cms_activity_registry_info.info_content_third
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public void setInfoContentThird(String infoContentThird) {
        this.infoContentThird = infoContentThird;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_registry_info.info_content_forth
     *
     * @return the value of cms_activity_registry_info.info_content_forth
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public String getInfoContentForth() {
        return infoContentForth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_registry_info.info_content_forth
     *
     * @param infoContentForth the value for cms_activity_registry_info.info_content_forth
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public void setInfoContentForth(String infoContentForth) {
        this.infoContentForth = infoContentForth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_registry_info.activity_id
     *
     * @return the value of cms_activity_registry_info.activity_id
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_registry_info.activity_id
     *
     * @param activityId the value for cms_activity_registry_info.activity_id
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_registry_info.user_id
     *
     * @return the value of cms_activity_registry_info.user_id
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_registry_info.user_id
     *
     * @param userId the value for cms_activity_registry_info.user_id
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_registry_info.state
     *
     * @return the value of cms_activity_registry_info.state
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_registry_info.state
     *
     * @param state the value for cms_activity_registry_info.state
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_registry_info.is_valid
     *
     * @return the value of cms_activity_registry_info.is_valid
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_registry_info.is_valid
     *
     * @param isValid the value for cms_activity_registry_info.is_valid
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_registry_info.create_time
     *
     * @return the value of cms_activity_registry_info.create_time
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_registry_info.create_time
     *
     * @param createTime the value for cms_activity_registry_info.create_time
     *
     * @mbggenerated Sun Mar 24 18:52:06 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}