package com.linkpets.core.model;

import java.util.Date;

public class CmsBanner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.banner_id
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    private String bannerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.activity_id
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    private String activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.banner_img_url
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    private String bannerImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.banner_redirect_url
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    private String bannerRedirectUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.sort
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.create_time
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.is_valid
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    private Integer isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.banner_id
     *
     * @return the value of cms_banner.banner_id
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    public String getBannerId() {
        return bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.banner_id
     *
     * @param bannerId the value for cms_banner.banner_id
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    public void setBannerId(String bannerId) {
        this.bannerId = bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.activity_id
     *
     * @return the value of cms_banner.activity_id
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.activity_id
     *
     * @param activityId the value for cms_banner.activity_id
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.banner_img_url
     *
     * @return the value of cms_banner.banner_img_url
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    public String getBannerImgUrl() {
        return bannerImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.banner_img_url
     *
     * @param bannerImgUrl the value for cms_banner.banner_img_url
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    public void setBannerImgUrl(String bannerImgUrl) {
        this.bannerImgUrl = bannerImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.banner_redirect_url
     *
     * @return the value of cms_banner.banner_redirect_url
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    public String getBannerRedirectUrl() {
        return bannerRedirectUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.banner_redirect_url
     *
     * @param bannerRedirectUrl the value for cms_banner.banner_redirect_url
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    public void setBannerRedirectUrl(String bannerRedirectUrl) {
        this.bannerRedirectUrl = bannerRedirectUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.sort
     *
     * @return the value of cms_banner.sort
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.sort
     *
     * @param sort the value for cms_banner.sort
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.create_time
     *
     * @return the value of cms_banner.create_time
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.create_time
     *
     * @param createTime the value for cms_banner.create_time
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.is_valid
     *
     * @return the value of cms_banner.is_valid
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.is_valid
     *
     * @param isValid the value for cms_banner.is_valid
     *
     * @mbggenerated Sat Mar 23 21:38:17 CST 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
}