package com.linkpets.core.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class CmsCoupon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_coupon.coupon_id
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    private String couponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_coupon.coupon_name
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    private String couponName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_coupon.coupon_en_name
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    private String couponEnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_coupon.coupon_type
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    private Integer couponType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_coupon.coupon_rule
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    private String couponRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_coupon.coupon_remind
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    private String couponRemind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_coupon.org_id
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_coupon.create_time
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_coupon.is_valid
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    private Integer isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_coupon.coupon_id
     *
     * @return the value of cms_coupon.coupon_id
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    public String getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_coupon.coupon_id
     *
     * @param couponId the value for cms_coupon.coupon_id
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    public void setCouponId(String couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_coupon.coupon_name
     *
     * @return the value of cms_coupon.coupon_name
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    public String getCouponName() {
        return couponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_coupon.coupon_name
     *
     * @param couponName the value for cms_coupon.coupon_name
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    public void setCouponName(String couponName) {
        this.couponName = couponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_coupon.coupon_en_name
     *
     * @return the value of cms_coupon.coupon_en_name
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    public String getCouponEnName() {
        return couponEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_coupon.coupon_en_name
     *
     * @param couponEnName the value for cms_coupon.coupon_en_name
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    public void setCouponEnName(String couponEnName) {
        this.couponEnName = couponEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_coupon.coupon_type
     *
     * @return the value of cms_coupon.coupon_type
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    public Integer getCouponType() {
        return couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_coupon.coupon_type
     *
     * @param couponType the value for cms_coupon.coupon_type
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    public void setCouponType(Integer couponType) {
        this.couponType = couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_coupon.coupon_rule
     *
     * @return the value of cms_coupon.coupon_rule
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    public String getCouponRule() {
        return couponRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_coupon.coupon_rule
     *
     * @param couponRule the value for cms_coupon.coupon_rule
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    public void setCouponRule(String couponRule) {
        this.couponRule = couponRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_coupon.coupon_remind
     *
     * @return the value of cms_coupon.coupon_remind
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    public String getCouponRemind() {
        return couponRemind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_coupon.coupon_remind
     *
     * @param couponRemind the value for cms_coupon.coupon_remind
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    public void setCouponRemind(String couponRemind) {
        this.couponRemind = couponRemind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_coupon.org_id
     *
     * @return the value of cms_coupon.org_id
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_coupon.org_id
     *
     * @param orgId the value for cms_coupon.org_id
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_coupon.create_time
     *
     * @return the value of cms_coupon.create_time
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_coupon.create_time
     *
     * @param createTime the value for cms_coupon.create_time
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_coupon.is_valid
     *
     * @return the value of cms_coupon.is_valid
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_coupon.is_valid
     *
     * @param isValid the value for cms_coupon.is_valid
     *
     * @mbggenerated Wed Mar 27 10:23:44 CST 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
}