package com.linkpets.core.model;

import java.util.Date;

public class CmsUserLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user_login.login_id
     *
     * @mbggenerated Sat May 18 20:40:12 CST 2019
     */
    private String loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user_login.user_id
     *
     * @mbggenerated Sat May 18 20:40:12 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user_login.login_date
     *
     * @mbggenerated Sat May 18 20:40:12 CST 2019
     */
    private Date loginDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user_login.login_id
     *
     * @return the value of cms_user_login.login_id
     *
     * @mbggenerated Sat May 18 20:40:12 CST 2019
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user_login.login_id
     *
     * @param loginId the value for cms_user_login.login_id
     *
     * @mbggenerated Sat May 18 20:40:12 CST 2019
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user_login.user_id
     *
     * @return the value of cms_user_login.user_id
     *
     * @mbggenerated Sat May 18 20:40:12 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user_login.user_id
     *
     * @param userId the value for cms_user_login.user_id
     *
     * @mbggenerated Sat May 18 20:40:12 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user_login.login_date
     *
     * @return the value of cms_user_login.login_date
     *
     * @mbggenerated Sat May 18 20:40:12 CST 2019
     */
    public Date getLoginDate() {
        return loginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user_login.login_date
     *
     * @param loginDate the value for cms_user_login.login_date
     *
     * @mbggenerated Sat May 18 20:40:12 CST 2019
     */
    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }
}