package com.linkpets.core.model;

import java.util.Date;

public class CmsUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.user_id
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.nick_name
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.mobile_phone
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.portrait
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    private String portrait;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.union_id
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    private String unionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.birthday
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.gender
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.location
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.intro
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.authenticated
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    private Integer authenticated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.is_valid
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    private Integer isValid;

    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_user.create_date
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    private Date createDate;

    private int followed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.user_id
     *
     * @return the value of cms_user.user_id
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.user_id
     *
     * @param userId the value for cms_user.user_id
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.nick_name
     *
     * @return the value of cms_user.nick_name
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.nick_name
     *
     * @param nickName the value for cms_user.nick_name
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.mobile_phone
     *
     * @return the value of cms_user.mobile_phone
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.mobile_phone
     *
     * @param mobilePhone the value for cms_user.mobile_phone
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.portrait
     *
     * @return the value of cms_user.portrait
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public String getPortrait() {
        return portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.portrait
     *
     * @param portrait the value for cms_user.portrait
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public void setPortrait(String portrait) {
        this.portrait = portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.union_id
     *
     * @return the value of cms_user.union_id
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.union_id
     *
     * @param unionId the value for cms_user.union_id
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.birthday
     *
     * @return the value of cms_user.birthday
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.birthday
     *
     * @param birthday the value for cms_user.birthday
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.gender
     *
     * @return the value of cms_user.gender
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.gender
     *
     * @param gender the value for cms_user.gender
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.location
     *
     * @return the value of cms_user.location
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.location
     *
     * @param location the value for cms_user.location
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.intro
     *
     * @return the value of cms_user.intro
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.intro
     *
     * @param intro the value for cms_user.intro
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.authenticated
     *
     * @return the value of cms_user.authenticated
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public Integer getAuthenticated() {
        return authenticated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.authenticated
     *
     * @param authenticated the value for cms_user.authenticated
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public void setAuthenticated(Integer authenticated) {
        this.authenticated = authenticated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.is_valid
     *
     * @return the value of cms_user.is_valid
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.is_valid
     *
     * @param isValid the value for cms_user.is_valid
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_user.create_date
     *
     * @return the value of cms_user.create_date
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_user.create_date
     *
     * @param createDate the value for cms_user.create_date
     *
     * @mbggenerated Sat May 25 12:14:03 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public int getFollowed() {
        return followed;
    }

    public void setFollowed(int followed) {
        this.followed = followed;
    }

    public String getOpenid() {
        return openid;
    }

    public void setOpenid(String openid) {
        this.openid = openid;
    }
}