package com.linkpets.core.model;

public class CommodityBrand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_brand.brand_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_brand.brand_name_chi
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String brandNameChi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_brand.brand_name_eng
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String brandNameEng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_brand.brand_name_tag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String brandNameTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_brand.logo_url
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String logoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_brand.discribe
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String discribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_brand.is_use
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String isUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_brand.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_brand.brand_id
     *
     * @return the value of commodity_brand.brand_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_brand.brand_id
     *
     * @param brandId the value for commodity_brand.brand_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setBrandId(String brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_brand.brand_name_chi
     *
     * @return the value of commodity_brand.brand_name_chi
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getBrandNameChi() {
        return brandNameChi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_brand.brand_name_chi
     *
     * @param brandNameChi the value for commodity_brand.brand_name_chi
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setBrandNameChi(String brandNameChi) {
        this.brandNameChi = brandNameChi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_brand.brand_name_eng
     *
     * @return the value of commodity_brand.brand_name_eng
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getBrandNameEng() {
        return brandNameEng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_brand.brand_name_eng
     *
     * @param brandNameEng the value for commodity_brand.brand_name_eng
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setBrandNameEng(String brandNameEng) {
        this.brandNameEng = brandNameEng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_brand.brand_name_tag
     *
     * @return the value of commodity_brand.brand_name_tag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getBrandNameTag() {
        return brandNameTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_brand.brand_name_tag
     *
     * @param brandNameTag the value for commodity_brand.brand_name_tag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setBrandNameTag(String brandNameTag) {
        this.brandNameTag = brandNameTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_brand.logo_url
     *
     * @return the value of commodity_brand.logo_url
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_brand.logo_url
     *
     * @param logoUrl the value for commodity_brand.logo_url
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_brand.discribe
     *
     * @return the value of commodity_brand.discribe
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getDiscribe() {
        return discribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_brand.discribe
     *
     * @param discribe the value for commodity_brand.discribe
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setDiscribe(String discribe) {
        this.discribe = discribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_brand.is_use
     *
     * @return the value of commodity_brand.is_use
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_brand.is_use
     *
     * @param isUse the value for commodity_brand.is_use
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setIsUse(String isUse) {
        this.isUse = isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_brand.del_flag
     *
     * @return the value of commodity_brand.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_brand.del_flag
     *
     * @param delFlag the value for commodity_brand.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}