package com.linkpets.core.model;

public class MallSpu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_spu.spu_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String spuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_spu.name
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_spu.spu_id
     *
     * @return the value of mall_spu.spu_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_spu.spu_id
     *
     * @param spuId the value for mall_spu.spu_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setSpuId(String spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_spu.name
     *
     * @return the value of mall_spu.name
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_spu.name
     *
     * @param name the value for mall_spu.name
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }
}