package com.linkpets.core.model;

import java.util.Date;

public class PetAlbum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_album.album_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String albumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_album.photo_path
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String photoPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_album.user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_album.pet_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String petId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_album.create_time
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_album.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_album.album_id
     *
     * @return the value of pet_album.album_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_album.album_id
     *
     * @param albumId the value for pet_album.album_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setAlbumId(String albumId) {
        this.albumId = albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_album.photo_path
     *
     * @return the value of pet_album.photo_path
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getPhotoPath() {
        return photoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_album.photo_path
     *
     * @param photoPath the value for pet_album.photo_path
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_album.user_id
     *
     * @return the value of pet_album.user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_album.user_id
     *
     * @param userId the value for pet_album.user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_album.pet_id
     *
     * @return the value of pet_album.pet_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_album.pet_id
     *
     * @param petId the value for pet_album.pet_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setPetId(String petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_album.create_time
     *
     * @return the value of pet_album.create_time
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_album.create_time
     *
     * @param createTime the value for pet_album.create_time
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_album.del_flag
     *
     * @return the value of pet_album.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_album.del_flag
     *
     * @param delFlag the value for pet_album.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}