package com.linkpets.core.model;

import java.util.Date;

public class PetLike {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_like.id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_like.pet_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String petId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_like.user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_like.create_datetime
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_like.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_like.id
     *
     * @return the value of pet_like.id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_like.id
     *
     * @param id the value for pet_like.id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_like.pet_id
     *
     * @return the value of pet_like.pet_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_like.pet_id
     *
     * @param petId the value for pet_like.pet_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setPetId(String petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_like.user_id
     *
     * @return the value of pet_like.user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_like.user_id
     *
     * @param userId the value for pet_like.user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_like.create_datetime
     *
     * @return the value of pet_like.create_datetime
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_like.create_datetime
     *
     * @param createDatetime the value for pet_like.create_datetime
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_like.del_flag
     *
     * @return the value of pet_like.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_like.del_flag
     *
     * @param delFlag the value for pet_like.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}