package com.linkpets.core.model;

public class PetSupplyConcat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_supply_concat.id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_supply_concat.supply_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String supplyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_supply_concat.user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_supply_concat.supply_status
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String supplyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_supply_concat.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_supply_concat.id
     *
     * @return the value of pet_supply_concat.id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_supply_concat.id
     *
     * @param id the value for pet_supply_concat.id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_supply_concat.supply_id
     *
     * @return the value of pet_supply_concat.supply_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getSupplyId() {
        return supplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_supply_concat.supply_id
     *
     * @param supplyId the value for pet_supply_concat.supply_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setSupplyId(String supplyId) {
        this.supplyId = supplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_supply_concat.user_id
     *
     * @return the value of pet_supply_concat.user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_supply_concat.user_id
     *
     * @param userId the value for pet_supply_concat.user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_supply_concat.supply_status
     *
     * @return the value of pet_supply_concat.supply_status
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getSupplyStatus() {
        return supplyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_supply_concat.supply_status
     *
     * @param supplyStatus the value for pet_supply_concat.supply_status
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setSupplyStatus(String supplyStatus) {
        this.supplyStatus = supplyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_supply_concat.del_flag
     *
     * @return the value of pet_supply_concat.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_supply_concat.del_flag
     *
     * @param delFlag the value for pet_supply_concat.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}