package com.linkpets.core.model;

import java.util.Date;

public class SdCatalogList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_catalog_list.id
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_catalog_list.catalog_id
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    private String catalogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_catalog_list.small_name
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    private String smallName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_catalog_list.image
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_catalog_list.sort
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_catalog_list.create_date
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_catalog_list.read_num
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    private Integer readNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_catalog_list.like_num
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    private Integer likeNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_catalog_list.id
     *
     * @return the value of sd_catalog_list.id
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_catalog_list.id
     *
     * @param id the value for sd_catalog_list.id
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_catalog_list.catalog_id
     *
     * @return the value of sd_catalog_list.catalog_id
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    public String getCatalogId() {
        return catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_catalog_list.catalog_id
     *
     * @param catalogId the value for sd_catalog_list.catalog_id
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    public void setCatalogId(String catalogId) {
        this.catalogId = catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_catalog_list.small_name
     *
     * @return the value of sd_catalog_list.small_name
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    public String getSmallName() {
        return smallName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_catalog_list.small_name
     *
     * @param smallName the value for sd_catalog_list.small_name
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    public void setSmallName(String smallName) {
        this.smallName = smallName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_catalog_list.image
     *
     * @return the value of sd_catalog_list.image
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_catalog_list.image
     *
     * @param image the value for sd_catalog_list.image
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_catalog_list.sort
     *
     * @return the value of sd_catalog_list.sort
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_catalog_list.sort
     *
     * @param sort the value for sd_catalog_list.sort
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_catalog_list.create_date
     *
     * @return the value of sd_catalog_list.create_date
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_catalog_list.create_date
     *
     * @param createDate the value for sd_catalog_list.create_date
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_catalog_list.read_num
     *
     * @return the value of sd_catalog_list.read_num
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    public Integer getReadNum() {
        return readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_catalog_list.read_num
     *
     * @param readNum the value for sd_catalog_list.read_num
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    public void setReadNum(Integer readNum) {
        this.readNum = readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_catalog_list.like_num
     *
     * @return the value of sd_catalog_list.like_num
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    public Integer getLikeNum() {
        return likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_catalog_list.like_num
     *
     * @param likeNum the value for sd_catalog_list.like_num
     *
     * @mbggenerated Wed Aug 21 23:47:51 CST 2019
     */
    public void setLikeNum(Integer likeNum) {
        this.likeNum = likeNum;
    }
}