package com.linkpets.core.model;

import java.util.Date;

public class ShareRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_record.record_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_record.user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_record.target_user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String targetUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_record.type
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_record.create_time
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_record.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_record.record_id
     *
     * @return the value of share_record.record_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_record.record_id
     *
     * @param recordId the value for share_record.record_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_record.user_id
     *
     * @return the value of share_record.user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_record.user_id
     *
     * @param userId the value for share_record.user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_record.target_user_id
     *
     * @return the value of share_record.target_user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getTargetUserId() {
        return targetUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_record.target_user_id
     *
     * @param targetUserId the value for share_record.target_user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setTargetUserId(String targetUserId) {
        this.targetUserId = targetUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_record.type
     *
     * @return the value of share_record.type
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_record.type
     *
     * @param type the value for share_record.type
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_record.create_time
     *
     * @return the value of share_record.create_time
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_record.create_time
     *
     * @param createTime the value for share_record.create_time
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_record.del_flag
     *
     * @return the value of share_record.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_record.del_flag
     *
     * @param delFlag the value for share_record.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}