package com.linkpets.core.model;

import java.util.Date;

public class SysChain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chain.chain_id
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    private String chainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chain.chain_name
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    private String chainName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chain.chain_address
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    private String chainAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chain.chain_phone
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    private String chainPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chain.chain_code
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    private String chainCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chain.org_id
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chain.oper_user_id
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    private String operUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chain.create_time
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chain.update_time
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chain.is_valid
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    private Integer isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chain.chain_id
     *
     * @return the value of sys_chain.chain_id
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    public String getChainId() {
        return chainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chain.chain_id
     *
     * @param chainId the value for sys_chain.chain_id
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    public void setChainId(String chainId) {
        this.chainId = chainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chain.chain_name
     *
     * @return the value of sys_chain.chain_name
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    public String getChainName() {
        return chainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chain.chain_name
     *
     * @param chainName the value for sys_chain.chain_name
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    public void setChainName(String chainName) {
        this.chainName = chainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chain.chain_address
     *
     * @return the value of sys_chain.chain_address
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    public String getChainAddress() {
        return chainAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chain.chain_address
     *
     * @param chainAddress the value for sys_chain.chain_address
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    public void setChainAddress(String chainAddress) {
        this.chainAddress = chainAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chain.chain_phone
     *
     * @return the value of sys_chain.chain_phone
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    public String getChainPhone() {
        return chainPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chain.chain_phone
     *
     * @param chainPhone the value for sys_chain.chain_phone
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    public void setChainPhone(String chainPhone) {
        this.chainPhone = chainPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chain.chain_code
     *
     * @return the value of sys_chain.chain_code
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    public String getChainCode() {
        return chainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chain.chain_code
     *
     * @param chainCode the value for sys_chain.chain_code
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    public void setChainCode(String chainCode) {
        this.chainCode = chainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chain.org_id
     *
     * @return the value of sys_chain.org_id
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chain.org_id
     *
     * @param orgId the value for sys_chain.org_id
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chain.oper_user_id
     *
     * @return the value of sys_chain.oper_user_id
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    public String getOperUserId() {
        return operUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chain.oper_user_id
     *
     * @param operUserId the value for sys_chain.oper_user_id
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    public void setOperUserId(String operUserId) {
        this.operUserId = operUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chain.create_time
     *
     * @return the value of sys_chain.create_time
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chain.create_time
     *
     * @param createTime the value for sys_chain.create_time
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chain.update_time
     *
     * @return the value of sys_chain.update_time
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chain.update_time
     *
     * @param updateTime the value for sys_chain.update_time
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chain.is_valid
     *
     * @return the value of sys_chain.is_valid
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chain.is_valid
     *
     * @param isValid the value for sys_chain.is_valid
     *
     * @mbggenerated Fri Apr 05 15:52:16 CST 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
}