package com.linkpets.core.model;

import java.util.Date;

public class SysOrg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.org_id
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.org_name
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.org_code
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.org_logo
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    private String orgLogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.oper_user_id
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    private String operUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.create_time
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.update_time
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.is_valid
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    private Integer isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.org_id
     *
     * @return the value of sys_org.org_id
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.org_id
     *
     * @param orgId the value for sys_org.org_id
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.org_name
     *
     * @return the value of sys_org.org_name
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.org_name
     *
     * @param orgName the value for sys_org.org_name
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.org_code
     *
     * @return the value of sys_org.org_code
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.org_code
     *
     * @param orgCode the value for sys_org.org_code
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.org_logo
     *
     * @return the value of sys_org.org_logo
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    public String getOrgLogo() {
        return orgLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.org_logo
     *
     * @param orgLogo the value for sys_org.org_logo
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    public void setOrgLogo(String orgLogo) {
        this.orgLogo = orgLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.oper_user_id
     *
     * @return the value of sys_org.oper_user_id
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    public String getOperUserId() {
        return operUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.oper_user_id
     *
     * @param operUserId the value for sys_org.oper_user_id
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    public void setOperUserId(String operUserId) {
        this.operUserId = operUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.create_time
     *
     * @return the value of sys_org.create_time
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.create_time
     *
     * @param createTime the value for sys_org.create_time
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.update_time
     *
     * @return the value of sys_org.update_time
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.update_time
     *
     * @param updateTime the value for sys_org.update_time
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.is_valid
     *
     * @return the value of sys_org.is_valid
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.is_valid
     *
     * @param isValid the value for sys_org.is_valid
     *
     * @mbggenerated Thu Apr 04 10:42:35 CST 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
}