package com.linkpets.core.model;

public class UserShoppingAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_shopping_address.id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_shopping_address.user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_shopping_address.receiver_name
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_shopping_address.receiver_phone
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String receiverPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_shopping_address.receiver_address
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String receiverAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_shopping_address.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_shopping_address.default_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String defaultFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_shopping_address.province
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_shopping_address.city
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_shopping_address.county
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String county;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_shopping_address.id
     *
     * @return the value of user_shopping_address.id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_shopping_address.id
     *
     * @param id the value for user_shopping_address.id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_shopping_address.user_id
     *
     * @return the value of user_shopping_address.user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_shopping_address.user_id
     *
     * @param userId the value for user_shopping_address.user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_shopping_address.receiver_name
     *
     * @return the value of user_shopping_address.receiver_name
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_shopping_address.receiver_name
     *
     * @param receiverName the value for user_shopping_address.receiver_name
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_shopping_address.receiver_phone
     *
     * @return the value of user_shopping_address.receiver_phone
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_shopping_address.receiver_phone
     *
     * @param receiverPhone the value for user_shopping_address.receiver_phone
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_shopping_address.receiver_address
     *
     * @return the value of user_shopping_address.receiver_address
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_shopping_address.receiver_address
     *
     * @param receiverAddress the value for user_shopping_address.receiver_address
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_shopping_address.del_flag
     *
     * @return the value of user_shopping_address.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_shopping_address.del_flag
     *
     * @param delFlag the value for user_shopping_address.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_shopping_address.default_flag
     *
     * @return the value of user_shopping_address.default_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getDefaultFlag() {
        return defaultFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_shopping_address.default_flag
     *
     * @param defaultFlag the value for user_shopping_address.default_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setDefaultFlag(String defaultFlag) {
        this.defaultFlag = defaultFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_shopping_address.province
     *
     * @return the value of user_shopping_address.province
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_shopping_address.province
     *
     * @param province the value for user_shopping_address.province
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_shopping_address.city
     *
     * @return the value of user_shopping_address.city
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_shopping_address.city
     *
     * @param city the value for user_shopping_address.city
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_shopping_address.county
     *
     * @return the value of user_shopping_address.county
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_shopping_address.county
     *
     * @param county the value for user_shopping_address.county
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setCounty(String county) {
        this.county = county;
    }
}