package com.linkpets.core.model;

import java.util.Date;

public class UserRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.record_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.title
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.content
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.images
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String images;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.recommend
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.create_time
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.check_state
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String checkState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.memo
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.type
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.location
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.detail_location
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String detailLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.lat
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.lng
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.check_by
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String checkBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.check_datetime
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private Date checkDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_record.city
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String city;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.record_id
     *
     * @return the value of user_record.record_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.record_id
     *
     * @param recordId the value for user_record.record_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.title
     *
     * @return the value of user_record.title
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.title
     *
     * @param title the value for user_record.title
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.content
     *
     * @return the value of user_record.content
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.content
     *
     * @param content the value for user_record.content
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.images
     *
     * @return the value of user_record.images
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.images
     *
     * @param images the value for user_record.images
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setImages(String images) {
        this.images = images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.recommend
     *
     * @return the value of user_record.recommend
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.recommend
     *
     * @param recommend the value for user_record.recommend
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setRecommend(String recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.user_id
     *
     * @return the value of user_record.user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.user_id
     *
     * @param userId the value for user_record.user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.create_time
     *
     * @return the value of user_record.create_time
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.create_time
     *
     * @param createTime the value for user_record.create_time
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.check_state
     *
     * @return the value of user_record.check_state
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getCheckState() {
        return checkState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.check_state
     *
     * @param checkState the value for user_record.check_state
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setCheckState(String checkState) {
        this.checkState = checkState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.memo
     *
     * @return the value of user_record.memo
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.memo
     *
     * @param memo the value for user_record.memo
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.type
     *
     * @return the value of user_record.type
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.type
     *
     * @param type the value for user_record.type
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.location
     *
     * @return the value of user_record.location
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.location
     *
     * @param location the value for user_record.location
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.detail_location
     *
     * @return the value of user_record.detail_location
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getDetailLocation() {
        return detailLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.detail_location
     *
     * @param detailLocation the value for user_record.detail_location
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setDetailLocation(String detailLocation) {
        this.detailLocation = detailLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.lat
     *
     * @return the value of user_record.lat
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.lat
     *
     * @param lat the value for user_record.lat
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setLat(String lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.lng
     *
     * @return the value of user_record.lng
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.lng
     *
     * @param lng the value for user_record.lng
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setLng(String lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.check_by
     *
     * @return the value of user_record.check_by
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getCheckBy() {
        return checkBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.check_by
     *
     * @param checkBy the value for user_record.check_by
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setCheckBy(String checkBy) {
        this.checkBy = checkBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.check_datetime
     *
     * @return the value of user_record.check_datetime
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public Date getCheckDatetime() {
        return checkDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.check_datetime
     *
     * @param checkDatetime the value for user_record.check_datetime
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setCheckDatetime(Date checkDatetime) {
        this.checkDatetime = checkDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.del_flag
     *
     * @return the value of user_record.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.del_flag
     *
     * @param delFlag the value for user_record.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_record.city
     *
     * @return the value of user_record.city
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_record.city
     *
     * @param city the value for user_record.city
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setCity(String city) {
        this.city = city;
    }
}