package com.linkpets.core.model;

import java.util.Date;

public class UserTemp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_temp.user_temp_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String userTempId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_temp.open_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_temp.create_time
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_temp.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_temp.user_temp_id
     *
     * @return the value of user_temp.user_temp_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getUserTempId() {
        return userTempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_temp.user_temp_id
     *
     * @param userTempId the value for user_temp.user_temp_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setUserTempId(String userTempId) {
        this.userTempId = userTempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_temp.open_id
     *
     * @return the value of user_temp.open_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_temp.open_id
     *
     * @param openId the value for user_temp.open_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_temp.create_time
     *
     * @return the value of user_temp.create_time
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_temp.create_time
     *
     * @param createTime the value for user_temp.create_time
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_temp.del_flag
     *
     * @return the value of user_temp.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_temp.del_flag
     *
     * @param delFlag the value for user_temp.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}