package com.linkpets.core.model;

import java.util.Date;

public class UserExploreHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_explore_history.history_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private Integer historyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_explore_history.explore_datetime
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private Date exploreDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_explore_history.pet_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String petId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_explore_history.user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_explore_history.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_explore_history.point_name
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String pointName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_explore_history.point_star
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private Integer pointStar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_explore_history.longitude
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_explore_history.latitude
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_explore_history.reward
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    private String reward;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_explore_history.history_id
     *
     * @return the value of user_explore_history.history_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public Integer getHistoryId() {
        return historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_explore_history.history_id
     *
     * @param historyId the value for user_explore_history.history_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setHistoryId(Integer historyId) {
        this.historyId = historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_explore_history.explore_datetime
     *
     * @return the value of user_explore_history.explore_datetime
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public Date getExploreDatetime() {
        return exploreDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_explore_history.explore_datetime
     *
     * @param exploreDatetime the value for user_explore_history.explore_datetime
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setExploreDatetime(Date exploreDatetime) {
        this.exploreDatetime = exploreDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_explore_history.pet_id
     *
     * @return the value of user_explore_history.pet_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_explore_history.pet_id
     *
     * @param petId the value for user_explore_history.pet_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setPetId(String petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_explore_history.user_id
     *
     * @return the value of user_explore_history.user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_explore_history.user_id
     *
     * @param userId the value for user_explore_history.user_id
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_explore_history.del_flag
     *
     * @return the value of user_explore_history.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_explore_history.del_flag
     *
     * @param delFlag the value for user_explore_history.del_flag
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_explore_history.point_name
     *
     * @return the value of user_explore_history.point_name
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getPointName() {
        return pointName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_explore_history.point_name
     *
     * @param pointName the value for user_explore_history.point_name
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setPointName(String pointName) {
        this.pointName = pointName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_explore_history.point_star
     *
     * @return the value of user_explore_history.point_star
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public Integer getPointStar() {
        return pointStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_explore_history.point_star
     *
     * @param pointStar the value for user_explore_history.point_star
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setPointStar(Integer pointStar) {
        this.pointStar = pointStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_explore_history.longitude
     *
     * @return the value of user_explore_history.longitude
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_explore_history.longitude
     *
     * @param longitude the value for user_explore_history.longitude
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_explore_history.latitude
     *
     * @return the value of user_explore_history.latitude
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_explore_history.latitude
     *
     * @param latitude the value for user_explore_history.latitude
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_explore_history.reward
     *
     * @return the value of user_explore_history.reward
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public String getReward() {
        return reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_explore_history.reward
     *
     * @param reward the value for user_explore_history.reward
     *
     * @mbggenerated Fri Mar 15 18:40:44 CST 2019
     */
    public void setReward(String reward) {
        this.reward = reward;
    }
}